runs:
  using: 'composite'
  steps:
    - name: Stop existing service
      run: |
        source venv/bin/activate
        pm2 delete ${{ inputs.app-env }} || true
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Start server
      run: |
        source venv/bin/activate
        pm2 start app.py --name ${{ inputs.app-env }} -- --port ${{ inputs.app-port }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}