name: mdTestesanaRGabrens

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-pip-deps:
    name: Install Python dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout main repository for deployment pipeline
        uses: actions/checkout@v3.5.2
        with:
          path: deployment-pipeline

      - name: Checkout python-greetings repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        working-directory: python-greetings

  deploy-to-dev:
    name: Deploy to development environment
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Stop existing app
        run: pm2 delete greetings-app-dev || true
        working-directory: python-greetings

      - name: Start new app instance
        run: pm2 start app.py --name greetings-app-dev -- --port 7001
        working-directory: python-greetings

  tests-on-dev:
    name: Run tests on development environment
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/course-js-api-framework
          path: course-js-api-framework

      - name: Install Node.js dependencies
        run: npm install
        working-directory: course-js-api-framework

      - name: Run tests
        run: npm run greetings greetings_dev
        env:
          NODE_ENV: development
          URL: http://localhost:7001
        working-directory: course-js-api-framework