name: mdTestesanaRGabrens

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install Python dependencies
        run: pip install -r requirements.txt

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Dev
        run: echo "Deploying to Dev environment"

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run tests on Dev
        run: echo "Running tests on Dev environment"

  deploy-to-staging:
    needs: tests-on-dev
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Staging
        run: echo "Deploying to Staging environment"

  tests-on-staging:
    needs: deploy-to-staging
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run tests on Staging
        run: echo "Running tests on Staging environment"

  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Pre-prod
        run: echo "Deploying to Pre-prod environment"

  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run tests on Pre-prod
        run: echo "Running tests on Pre-prod environment"

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Production
        run: echo "Deploying to Production environment"

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run tests on Production
        run: echo "Running tests on Production environment"
