name: mdTestesanaRGabrens

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3.5.2
        with:
          ref: 'main'

      - name: Checkout python-greetings repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Install dependencies
        run: pip3 install -r requirements.txt
        working-directory: ./python-greetings

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3.5.2

      - name: Checkout python-greetings repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Stop existing service
        # run: pm2 delete greetings-app-dev || true
        run: pm2 delete greetings-app-dev; if ($LASTEXITCODE -ne 0) { $true }
        working-directory: ./python-greetings

      - name: Start new service
        run: pm2 start app.py --name greetings-app-dev -- --port 7001
        working-directory: ./python-greetings

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Run tests on Dev
        run: echo "Running tests on Dev environment"

  deploy-to-staging:
    needs: tests-on-dev
    runs-on: self-hosted
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3.5.2

      - name: Checkout python-greetings repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Stop existing service
        run: pm2 delete greetings-app-staging || true
        working-directory: ./python-greetings

      - name: Start new service
        run: pm2 start app.py --name greetings-app-staging -- --port 7002
        working-directory: ./python-greetings

  tests-on-staging:
    needs: deploy-to-staging
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Run tests on Staging
        run: echo "Running tests on Staging environment"

  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: self-hosted
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3.5.2

      - name: Checkout python-greetings repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Stop existing service
        run: pm2 delete greetings-app-preprod || true
        working-directory: ./python-greetings

      - name: Start new service
        run: pm2 start app.py --name greetings-app-preprod -- --port 7003
        working-directory: ./python-greetings

  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Run tests on Pre-prod
        run: echo "Running tests on Pre-prod environment"

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3.5.2

      - name: Checkout python-greetings repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Stop existing service
        run: pm2 delete greetings-app-prod || true
        working-directory: ./python-greetings

      - name: Start new service
        run: pm2 start app.py --name greetings-app-prod -- --port 7004
        working-directory: ./python-greetings

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Run tests on Production
        run: echo "Running tests on Production environment"
