name: mdTestesanaRGabrens

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-pip-deps:
    name: install pip dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3.5.2

      - name: Clone python-greetings repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Install dependencies
        run: pip3 install -r requirements.txt
        working-directory: python-greetings
        shell: bash

  deploy-to-dev:
    name: deploy to dev
    needs: install-pip-deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3.5.2

      - name: Clone python-greetings repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Stop existing application
        run: pm2 delete greetings-app-dev || true
        working-directory: python-greetings
        shell: bash

      - name: Start application
        run: pm2 start app.py --name greetings-app-dev -- --port 7001
        working-directory: python-greetings
        shell: bash

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3.5.2

      - name: Clone course-js-api-framework repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/course-js-api-framework
          path: course-js-api-framework

      - name: Install dependencies
        run: npm install
        working-directory: course-js-api-framework
        shell: bash

      - name: Run tests
        run: npm run greetings greetings_dev
        working-directory: course-js-api-framework
        shell: bash
