name: mdTestesanaRGabrens

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Clone python-greetings repository
      uses: actions/checkout@v3.5.2
      with:
        repository: 'mtararujs/python-greetings'
        path: 'python-greetings'
    - name: Install dependencies
      run: |
        echo "Installing all required dependencies..."
        cd python-greetings
        pip3 install -r requirements.txt
      working-directory: python-greetings

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Clone python-greetings repository for deployment
      uses: actions/checkout@v3.5.2
      with:
        repository: 'mtararujs/python-greetings'
        path: 'python-greetings'
    - name: Deploy to development environment
      run: |
        echo "Deploying application to development environment..."
        pm2 delete greetings-app-dev 2>$null
        pm2 start app.py --name greetings-app-dev -- -- --port 7001
      shell: pwsh
      working-directory: python-greetings

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Clone course-js-api-framework repository for tests
      uses: actions/checkout@v3.5.2
      with:
        repository: 'mtararujs/course-js-api-framework'
        path: 'course-js-api-framework'
    - name: Install dependencies and run tests
      run: |
        echo "Installing dependencies for testing..."
        cd course-js-api-framework
        npm install
        echo "Running tests on development environment..."
        npm run greetings greetings_dev
      working-directory: course-js-api-framework
